version: '3'
services:
  go:
    build:
      context: .
      dockerfile: DockerFile
    command: /bin/sh -c "go run src/*.go"
    ports:
      - 8080:80
    volumes:
      - .:/app
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306